---
config:
  uid: 1000
  gid: 1000
files:
  default:
    content: |
      TIMEOUT 50
      TOTALTIMEOUT 9000
      ONTIMEOUT local
      default local

      LABEL local
              MENU LABEL Boot local hard drive
              LOCALBOOT 0

    persistent: True

